apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecrets-sa.yaml
  # Optional: give your apps IRSA too if they call AWS APIs directly
  # - inference-api-sa.yaml
  # - indexer-sa.yaml
  # - web-sa.yaml
