apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: indexer-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: indexer-env
    creationPolicy: Owner
  data:
    - secretKey: PG_URL
      remoteRef:
        key: /crowdaudit/dev/indexer
        property: PG_URL
    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: /crowdaudit/dev/indexer
        property: KAFKA_BROKERS
    - secretKey: KAFKA_TOPIC
      remoteRef:
        key: /crowdaudit/dev/indexer
        property: KAFKA_TOPIC
    - secretKey: KAFKA_GROUP_ID
      remoteRef:
        key: /crowdaudit/dev/indexer
        property: KAFKA_GROUP_ID
    - secretKey: OS_URL
      remoteRef:
        key: /crowdaudit/dev/indexer
        property: OS_URL
    - secretKey: OS_INSECURE
      remoteRef:
        key: /crowdaudit/dev/indexer
        property: OS_INSECURE
