apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: inference-api-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: inference-api-env
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /crowdaudit/dev/inference-api
        property: DATABASE_URL
    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: /crowdaudit/dev/inference-api
        property: KAFKA_BROKERS
    - secretKey: ENABLE_OUTBOX_PUBLISHER
      remoteRef:
        key: /crowdaudit/dev/inference-api
        property: ENABLE_OUTBOX_PUBLISHER
